import './globals.css'
import Navbar from '@/components/NavBar'
import ShaderBackground from '@/components/ShaderBackground'
export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <ShaderBackground />
        <Navbar />
        <div >
          {children}
        </div>
      </body>
    </html>
  );
}