// /src/app/layout.js
import './globals.css';
import Navbar from '@/components/NavBar';
import ShaderBackground from '@/components/ShaderBackground';
import PageTransition from '@/components/PageTransition';

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <ShaderBackground />
        <div className="overlay"></div>
        <Navbar />
        <PageTransition>
          <div>
            {children}
          </div>
        </PageTransition>
      </body>
    </html>
  );
}
